### PR TITLE
Always place do-blocks in hanging position

### LINKED ISSUE #417: Expression-style "do" leads to strange output
It looks as though Ormolu prefers the trailing-style `do` instead of the expression-style `do`. That is,
```
main = do
  putStrLn "Hi!"
  putStrLn "I am a program!"
```
instead of
```
main =
  do putStrLn "Hi!"
     putStrLn "I am a program!"
```

However, formatting the latter results in the following:
```
main =
  do
    putStrLn "Hi!"
    putStrLn "I am a program!"
```
which seems to necessitate a manual pass to move all `do` keywords up to the previous line before automatically formatting. Perhaps an exemption from "respect the user's newlines" is in order in this particular case?

### PR DESCRIPTION
**Pull request by mrkkrp**
Close #417.

### CODE REVIEW

**Comment by neongreen** [comment]
Can you add a test case?

**Comment by mrkkrp** [comment]
This is a work in progress.

**Comment by mrkkrp** [comment]
I got it to work as I want, but there is a complication because of how comments interact with this feature. I'll return to this later.

**Comment by mrkkrp** [comment]
Closing for now.

**Pull request closed without merging**
