### PR TITLE
Add reference to the trailing comma problem and fourmolu

### PR DESCRIPTION
**Pull request by itsfarseen**
Ref: https://github.com/tweag/ormolu/issues/710#issuecomment-864436964

### CODE REVIEW

**Comment by mrkkrp** [comment]
Thanks for your interest! I think there is no problem with referencing fourmolu in the readme because it indeed may provide functionality that suits certain users better than what's available in Ormolu. However, I don't think it is fair to include a deliberate stylistic choice we made in Ormolu as a "limitation". If you look at the existing items in the list of limitations, you'll notice that they are all hard and genuine problems. The way commas are placed can be changed very easily and so it's not exactly the same kind of thing.

**Comment by itsfarseen** [comment]
> However, I don't think it is fair to include a deliberate stylistic choice we made in Ormolu as a "limitation". If you look at the existing items in the list of limitations, you'll notice that they are all hard and genuine problems.

Yeah, totally agree. I put it there because I couldn't find a better place to put.  
I have changed it to be a separate heading. But I feel that it does look kind a weird though.

**Comment by itsfarseen** [comment]
I have moved it under the Notes section. It felt weird to put `Comma placement` as a top level heading.

**Comment by mrkkrp** [comment]
I took the liberty to adjust the PR. I think the main point is that there are actively maintained forks of Ormolu, namley Fourmolu that might be of interest to the reader of the readme. I made a section called "forks" to talk about it.

**Pull request merged**
