### PR TITLE
Handle multi-operator fixity declarations in the extraction script

### PR DESCRIPTION
**Pull request by tbagrel1**

### CODE REVIEW

**Comment by mrkkrp** [comment]
Have you made sure that it indeed correctly parses multi-operator fixity declarations?

**Comment by tbagrel1** [comment]
>  Have you made sure that it indeed correctly parses multi-operator fixity declarations?

I tried it with `infixr 6 ====>>,====<<, ===>>> ,<<<===`, and I got them in the output map with the expected fixities.

**Review by mrkkrp — APPROVED** [review]

**Comment by tbagrel1** [comment]
FYI, there is no fixity declaration with multiple operators on the same line in the current hoogle database. So this change is only intended to future-proof the extraction script.

**Comment by mrkkrp** [comment]
What about e.g. https://hackage.haskell.org/package/base-4.16.0.0/docs/src/GHC.List.html ?

It has:

```haskell
infix  4 `elem`, `notElem`
```

Shouldn't it be accounted for?

**Comment by tbagrel1** [comment]
[base.txt](https://github.com/tweag/ormolu/files/7735907/base.txt)

I think that Hoogle might pre-process hackage source files, because I can't find
```haskell
infix 4 `elem`, `notElem`
```
in this file.

**Pull request merged**
