### PR TITLE
group StandaloneKindSignatures with type synonyms

### LINKED ISSUE #683: StandaloneKindSignatures: grouping does not work for type synonyms
With ormolu 0.1.4.1:

```haskell
type Bla :: Type
type Bla = Int
```
is transformed into
```haskell
type Bla :: Type

type Bla = Int

```
but I would expect it to be a fixed point.

This simply appears to be an oversight in #533.

This diff fixes the issue:

```diff
diff --git a/src/Ormolu/Printer/Meat/Declaration.hs b/src/Ormolu/Printer/Meat/Declaration.hs
index dba14d9..5415fe0 100644
--- a/src/Ormolu/Printer/Meat/Declaration.hs
+++ b/src/Ormolu/Printer/Meat/Declaration.hs
@@ -188,6 +188,7 @@ groupedDecls (L l_x x') (L l_y y') =
     (KindSignature n, DataDeclaration n') -> n == n'
     (KindSignature n, ClassDeclaration n') -> n == n'
     (KindSignature n, FamilyDeclaration n') -> n == n'
+    (KindSignature n, TypeSynonym n') -> n == n'
     -- Special case for TH splices, we look at locations
     (Splice, Splice) -> not (separatedByBlank id l_x l_y)
     -- This looks only at Haddocks, normal comments are handled elsewhere
@@ -247,7 +248,8 @@ pattern
   DataDeclaration,
   ClassDeclaration,
   KindSignature,
-  FamilyDeclaration ::
+  FamilyDeclaration,
+  TypeSynonym ::
     RdrName -> HsDecl GhcPs
 pattern InlinePragma n <- SigD NoExtField (InlineSig NoExtField (L _ n) _)
 pattern SpecializePragma n <- SigD NoExtField (SpecSig NoExtField (L _ n) _ _)
@@ -259,6 +261,7 @@ pattern DataDeclaration n <- TyClD NoExtField (DataDecl NoExtField (L _ n) _ _ _
 pattern ClassDeclaration n <- TyClD NoExtField (ClassDecl NoExtField _ (L _ n) _ _ _ _ _ _ _ _)
 pattern KindSignature n <- KindSigD NoExtField (StandaloneKindSig NoExtField (L _ n) _)
 pattern FamilyDeclaration n <- TyClD NoExtField (FamDecl NoExtField (FamilyDecl NoExtField _ (L _ n) _ _ _ _))
+pattern TypeSynonym n <- TyClD NoExtField (SynDecl NoExtField (L _ n) _ _ _)
 
 -- Declarations which can refer to multiple names
```

Can create a PR if desired.

### PR DESCRIPTION
**Pull request by amesgen**
Closes #683

### CODE REVIEW

**Review by mrkkrp — APPROVED** [review]

**Comment by amesgen** [comment]
Uh, the build now fails on GHC 8.6.5 and 8.8.4 with
```
src/Ormolu/Printer/Meat/Declaration.hs:170:3: error: [-Werror]
    Pattern match checker exceeded (2000000) iterations in
    a case alternative. (Use -fmax-pmcheck-iterations=n
    to set the maximun number of iterations to n)
    |
170 |   case (x', y') of
    |   ^^^^^^^^^^^^^^^^...
```
but succeeds on 8.10.3 (which I used locally initially).

This warning disappears (at least on 8.6.5) if I compile with `-fmax-pmcheck-iterations=3000000`.

**Comment by mrkkrp** [comment]
Yeah, I have seen that. I'll fix it up when I have time.

**Comment by amesgen** [comment]
Sorry for not catching that, it appears that CI did not run on this PR.

**Comment by mrkkrp** [comment]
It's not your fault, for security reasons CI doesn't run for PRs opened from forks.

**Pull request merged**
