### PR TITLE
Use mode instead of mean when calculating operator fixities

### PR DESCRIPTION
**Pull request by utdemir**
Related: #451.

When deciding on the fixity of an operator, we assign a score
based on some heuristics. When an operator is used multiple times
in an operator chain, we used to calculate the mean of its scores
to decide on the final fixity. However, this was prone to outliers.

In an example like this:

```haskell
b & c .~ d
  & e
    %~ f
        g
```

The first use of `&` is surrounded by other values, so we assign it
a higher score (binds tighter). However the second occurence is at
the beginning of a line, and this has a lower score. In the end, when
we average those two values the result binds tighter than `%~`, which
is not what we want.

This PR replaces the `average` method with a `mode` operation instead,
so it is less prone to outliers.

This PR fixes this specific issue (#451), and does not cause any change
on other test cases, but it might cause some diffs in the wild.

### CODE REVIEW

**Comment by neongreen** [comment]
Can you show how operators-out.hs would have looked before this PR?

**Comment by utdemir** [comment]
@neongreen `operators-out.hs` would look the same before this PR, but formatting it again would cause an idempotence issue by trying to reformat it as:

```haskell
a =
  b & c .~ d
    & e
    %~ f
      g
```

**Comment by mrkkrp** [comment]
Could you please rebase on `master`? Does this PR in fact fix #451 completely so that it can be closed when we merge this?

**Comment by utdemir** [comment]
Thanks Mark, I rebased the PR. It fixes the idempotency issue on #451, but does not address the stylistic issues also mentioned there.

**Comment by mrkkrp** [comment]
@utdemir Please include your descriptions in the commit message next time, I think they deserve to stay in commit history, not just on GitHub :-)

**Pull request merged**
