### PR TITLE
Replace “idempotency” with “idempotence”

### PR DESCRIPTION
**Pull request by mrkkrp**

### CODE REVIEW

**Comment by mheinzel** [comment]
Would it maybe be possible to accept both versions for the next release and only then remove the old one?

**Comment by mrkkrp** [comment]
We are iterating fast and Ormolu is still unstable. No stability guarantees are given so that we can keep things simple.

**Comment by mrkkrp** [comment]
You can use `-c` (the short form) which works with both versions.

**Comment by mheinzel** [comment]
Cool, no problem.

**Pull request merged**
