### PR TITLE
Implement rendering of instance declarations

### PR DESCRIPTION
**Pull request by yumiova**
This pull request implements half of #49. Specifically, it deals with pretty printing instance declarations and most structures needed to support that. This includes pretty printing of associated types (and therefore also type family instances.) However, this _does not_ include pretty printing of associated data types.

Pretty printing of type class declarations is to be dealt with at a later time.

Instances are formatted such that indentation hangs after the `instance`. Namely,

```haskell
instance Eq a
         => Eq [a] where
```

To support pretty printing associated types, the function `p_tyFamInstEqn` was exported from the appropriate module. This was done to avoid redundant code duplication.

As for supporting pretty printing of associated data types: there is a potential (but unimplemented) solution that works while minimizing code duplication by changing the `p_dataDecl` function, which currently has the signature:

```haskell
p_dataDecl :: Located RdrName -> LHsQTyVars GhcPs -> HsDataDefn GhcPs -> R ()
```

If the parameters to `p_dataDecl` instead were any `HsType`, then the associated data patterns could be pretty printed using `p_dataDecl`. Fortunately, type variables can be directly represented in `HsType`s.

Furthermore, if `p_dataDecl` took an extra parameter to represent the context (or style) it is placed in, it would be trivial to support open data family instances as well, providing a final signature:

```haskell
p_dataDecl :: FamilyStyle -> Located RdrName -> [LHsType GhcPs] -> HsDataDefn GhcPs -> R ()
```

In principle, making this change should not take me long at all, and would give complete support for both associated data and open data family instances.

That said, I feel like larger changes to e.g. type signatures and use cases like this should be agreed upon ahead of time. Hence, why I have not implemented this yet.

This branch has had its commit history squashed. See [yumiova:yumiova/instance-declaration](https://github.com/yumiova/ormolu/tree/yumiova/instance-declaration) for the original commit history.

### CODE REVIEW

**Comment by yumiova** [comment]
Just realised some tests I need to add; give me a few minutes.

**Comment by mrkkrp** [comment]
Take your time, I'm done for today, will review it tomorrow. I also sent you an invitation to become a collaborator. This will give you write access to the repo.

**Comment by mrkkrp** [comment]
This looks good. I went ahead and relaxed comparison of ASTs to allow differences in `SourceText`s, which should be pretty harmless.

I think it makes sense to change `p_dataDecl` in the way you describe and so gain support for data family instances too. Could you add this in this PR? Once that is added, I think we can merge.

**Comment by yumiova** [comment]
OK, this took me a little bit longer than expected, but support for associated data types and open data family instances should now be working.

**Pull request merged**
