### PR TITLE
Fix GHC warnings

### PR DESCRIPTION
**Pull request by cblp**

### CODE REVIEW

**Comment by mrkkrp** [comment]
Are these GHC warnings or HLint warnings?

**Comment by cblp** [comment]
GHC warnings, a typo fix, and a bit of HLint warnings, sorry. Should I remove them?

**Comment by mrkkrp** [comment]
No, I just asked.

**Comment by mrkkrp** [comment]
Thank you for opening the PR. What is disturbing is that those thing were not caught by CI. In fact this was because I forgot to enable the `dev` flag in Nix. I added the change to avoid the problem in the future. Going to merge when it's green.

**Pull request merged**
